### ISSUE TITLE
Release 1.7 and deploy to PyPi

### ISSUE THREAD

**Issue by JonasVautherin** [hubo1016/aiogrpc#14]
With the latest commits fixing the build for Python 3.8, I think it would be worth releasing 1.7 and deploying it to PyPi :innocent:.

**Comment by hubo1016** [comment]
Done, please test

**Comment by JonasVautherin** [comment]
Working now with 1.7 from PyPi (note that you should probably tag 1.7 on this git repo as well).

Thanks a lot! :tada:
