### ISSUE TITLE
Add backwards compatibility to Python 3.5

### ISSUE THREAD

**Issue by xvzf** [hubo1016/aiogrpc#5]
Hi,

How are you thinking about backwards compatibility to Python 3.5?
I  have a project where I unfortunately have to support Python 3.5..

Cheers,
Matthias

**Comment by hubo1016** [comment]
Though not tested, it seems that the code itself is Python 3.5 compatible (but the test cases are not). But in Python 3.5, you cannot use async generators, so it is somehow difficult to write a stream method. Anything besides that should work.

Did you meet any problems?

**Comment by xvzf** [comment]
Not yet - I've build the code ontop of async generators; I wasn't aware that this feature was added to 3.6!
I'll write some test cases for Python 3.5 and think about using a different approach for processing streams!

I'll PR when I'm done! :-)

**Comment by xvzf** [comment]
That's how I would implement an async generator in python 3.5:
https://gist.github.com/xvzf/985d07081594b0a4cbe63afc2fa6c2d8

It would be as easy as
```python
@async_generator
async def test():
    while True:
        await _yield("ToDo")
```

It works with the standard `async with` but not with aiogrpc yet. I'll have to investigate where it's failing!

**Comment by xvzf** [comment]
We just dropped support for Python 3.5.!

**Comment by hubo1016** [comment]
@xvzf Good choice 👍
